#!/bin/sh
#$ -m bea         # send email or start, end and abortion
#$ -j y            # combines standard output and standard error
#$ -cwd           # Set the working directory for the job to the current directory
#$ -pe smp 16      # Request 16 cores
#$ -l h_rt=72:0:0 # Request 72 hour runtime
#$ -l h_vmem=16G   # Request 16GB RAM
./assemble.sh
